parameters:
    database_driver: pdo_sqlite
    database_host: 127.0.0.1
    database_port: 
    database_name: Actorzzz
    database_user: 
    database_password: null

    secret: ThisTokenIsNotSoSecretChangeIt
    locale:            en
    
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user:
    mailer_password: