Actorzzz:
    resource: "@ActorzzzBundle/Resources/config/routing.yml"
    prefix:   /

home:
    pattern:   /home

login:
    pattern:   /login
    defaults:  { _controller: ActorzzzBundle:Security:login }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout
