<?php

namespace ActorzzzBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ActorzzzRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActorzzzRepository extends EntityRepository
{
}
