<?php

namespace ActorzzzBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FormulaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormulaireRepository extends EntityRepository
{
}
