<?php

namespace ActorzzzBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * voteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class voteRepository extends EntityRepository
{
}
